const TLS_VERSION_1_2 = 0x0303;
const TLS_RSA_WITH_AES_128_CBC_SHA = 0x002f;
const TLS_RSA_WITH_AES_128_CBC_SHA256 = 0x003c;
const SUPPORTED_CIPHER_SUITES = [TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA];
const DEFAULT_COMPRESSION_METHODS = [0x00];
const DEFAULT_SIGNATURE_ALGORITHMS = [
  { hash: 0x04, signature: 0x01 },
  { hash: 0x02, signature: 0x01 },
];
const CIPHER_SUITE_TO_OPENSSL_NAME = {
  [TLS_RSA_WITH_AES_128_CBC_SHA]: 'AES128-SHA',
  [TLS_RSA_WITH_AES_128_CBC_SHA256]: 'AES128-SHA256',
};
const OPENSSL_CIPHER_NAME_TO_SUITE = {
  'AES128-SHA': TLS_RSA_WITH_AES_128_CBC_SHA,
  'AES128-SHA256': TLS_RSA_WITH_AES_128_CBC_SHA256,
  TLS_RSA_WITH_AES_128_CBC_SHA,
  TLS_RSA_WITH_AES_128_CBC_SHA256,
};

const CIPHER_SPECS = {
  [TLS_RSA_WITH_AES_128_CBC_SHA]: {
    macAlgorithm: 'sha1',
    macKeyLength: 20,
    macLength: 20,
  },
  [TLS_RSA_WITH_AES_128_CBC_SHA256]: {
    macAlgorithm: 'sha256',
    macKeyLength: 32,
    macLength: 32,
  },
};

module.exports = {
  TLS_VERSION_1_2,
  TLS_RSA_WITH_AES_128_CBC_SHA,
  TLS_RSA_WITH_AES_128_CBC_SHA256,
  SUPPORTED_CIPHER_SUITES,
  DEFAULT_COMPRESSION_METHODS,
  DEFAULT_SIGNATURE_ALGORITHMS,
  CIPHER_SUITE_TO_OPENSSL_NAME,
  OPENSSL_CIPHER_NAME_TO_SUITE,
  CIPHER_SPECS,
};
